Adventum/Controllers/EventReservationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Adventum.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace Adventum.Controllers;

[Authorize]
public class EventReservationsController : Controller
{
    private readonly AdventureContext _context;
    private readonly UserManager<User> _userManager;

    public EventReservationsController(AdventureContext context, UserManager<User> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        string currentUser = _userManager.GetUserId(User);

        IQueryable<EventReservation> query = User.IsInRole(Constants.AdministratorRole)
            ? _context.EventReservations.AsQueryable()
            : _context.EventReservations.Where(x => x.UserId == currentUser);

        List<EventReservation> result = await query
            .Include(er => er.User)
            .Include(er => er.Event)
            .ThenInclude(e => e.SportActivity)
            .ToListAsync();
        
        ViewBag.ImageUrl = "~/images/bungee/";

        return View(result);
    }

    [HttpGet]
    public async Task<IActionResult> Create(int sportActivityId)
    {
        var user = await _userManager.GetUserAsync(User);

        var tomorrow = DateTime.Now.AddDays(1);

        var model = new UserReservationModel
        {
            UserId = user.Id,
            FirstName = user.FirstName,
            LastName = user.LastName,
            Email = user.Email,
            Date = tomorrow,
            SportActivityId = sportActivityId
        };

        return View(model);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(UserReservationModel model)
    {
        var evt = await _context.Events.FirstOrDefaultAsync(e => e.SportActivityId == model.SportActivityId);

        _context.EventReservations.Add(new EventReservation
        {
            UserId = model.UserId,
            EventId = evt.Id,
            Date = model.Date,
            ParticipantsCount = model.ParticipantCount
        });


        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> Delete(int id)
    {
        if (id == null || _context.EventReservations == null)
        {
            return NotFound();
        }

        var eventReservation = await _context.EventReservations
            .Include(e => e.Event)
            .Include(u => u.User)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (eventReservation == null)
        {
            return NotFound();
        }

        return View(eventReservation);
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var eventReservation = await _context.EventReservations
            .Include(u => u.User)
            .FirstOrDefaultAsync(x => x.Id == id);

        if (eventReservation == null)
            return RedirectToAction(nameof(Index));

        _context.EventReservations.Remove(eventReservation);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
    }
}

Adventum/Controllers/HomeController.cs
using System.ComponentModel.DataAnnotations;
using Adventum.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Adventum.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic.CompilerServices;

namespace Adventum.Controllers
{
    public class HomeController : Controller
    {
        private readonly UserManager<User> _userManager;
        
        private readonly AdventureContext _context;

        public HomeController(UserManager<User> userManager, AdventureContext context)
        {
            _userManager = userManager;
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Gallery()
        {
            return View();
        }
        public IActionResult Video()
        {
            return View();
        }
        public IActionResult AboutUs()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            return View();
        }
       
        public async Task<IActionResult> Booking()
        {
            var events = await _context.Events
                .Include(s => s.SportActivity)
                .Include(l => l.Location)
                .ToListAsync();
            return View(events);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }


    public class UserReservationModel
    {
        public string UserId { get; set; }
        
        [Display(Name = "Име")]
        [Editable(false)]
        public string FirstName { get; set; }
        
        [Display(Name = "Фамилия")]
        [Editable(false)]
        public string LastName { get; set; }
        
        [Display(Name = "Имейл")]
        [Editable(false)]
        public string Email { get; set; }
        
        [DataType(DataType.Date)]
        [Display(Name = "Избери дата")]
        public DateTime Date { get; set; }

        [Range(1, Int32.MaxValue)]
        [Display(Name = "Брой участници")]
        public int ParticipantCount { get; set; }
        
        public int SportActivityId { get; set; }
    }
}

Adventum/Controllers/SportsController.cs
using System.ComponentModel.DataAnnotations;
using Adventum.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Adventum.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic.CompilerServices;


namespace Adventum.Controllers
{
    public class SportsController : Controller
    {

       

        private readonly AdventureContext _context;

        public SportsController(AdventureContext context)
        {
            
            _context = context;
        }
        public IActionResult ATVpage()
        {
            return View();
        }
        public IActionResult BalloonPage()
        {
            return View();
        }
        public IActionResult BungeePage()
        {
            return View();
        }
        public IActionResult ClimbPage()
        {
            return View();
        }
        public IActionResult ParaPage()
        {
            return View();
        }
        public IActionResult RaftingPage()
        {
            return View();
        }
        public IActionResult SkydivePage()
        {
            return View();
        }
        public IActionResult SnowPage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Adventum/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "За нас";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adventum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/aboutUs.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Adventum.styles.css" asp-append-version="true" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
</head>
<body>
    <section>
        <div class="container">
            <div class="content-section">
                <div class="title">
                    <h1>За нас</h1>
                </div>
                <div class="content">
                    <h3>
                        Adventum е компания от хора, работещи за забавата, екстремността и различното.
                        Семейството ни съществува вече 10 години и поддържа сайта ни в класацията на топ 5 най-добри сайтове за екстремности.
                        Обичаме непредвиденото, изненадите и природата. Ако смяташ, че си приличаме в това, побързай да се свържеш с нас и не изпускай забавата!
                    </h3>
                </div>
                <div class="social">
                    <a href=""><i class="bi bi-facebook"></i></a>
                    <a href=""><i class="bi bi-instagram"></i></a>
                    <a href=""><i class="bi bi-pinterest"></i></a>
                </div>
            </div>
            <div class="image-section">
                <img src="/photos/ADVENTUM.png" />
            </div>
        </div>
    </section>
    <section>
        <div class="container-2">
            <div class="content-box-lg">
                <div class="container-3">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="about-item text-center">
                                <i class="bi bi-book"></i>
                                <h3>МИСИЯ</h3>
                                <hr />
                                <p>
                                    Мисията ни е да накараме все повече хора да излязат от зоната си на комфорт.
                                    Да изпробват нещо ново, екстремно и красиво.
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="about-item text-center">
                                <i class="bi bi-globe"></i>
                                <h3>ВИЖДАНЕ</h3>
                                <hr />
                                <p>
                                    Мотивирани сме да продължаваме да бъдем част от живота на всеки един от вас,
                                    успявайки да запечатаме вашите незабравими моменти - това са нашите цели.
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="about-item text-center">
                                <i class="bi bi-pencil"></i>
                                <h3>ПОСТИЖЕНИЯ</h3>
                                <hr />
                                <p>
                                    За нас всяка една усмивка на лицата ви е постижение, с което сме горди и целим да бъдат все повече усмивки за в бъдеще.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
</html>

Adventum/Views/Home/Booking.cshtml

@model IEnumerable<Event>
@{
    ViewData["Title"] = "РЕЗЕРВИРАЙ";
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/booking.css" asp-append-version="true" />

    <link rel="stylesheet" href="~/Adventum.styles.css" asp-append-version="true" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

</head>
<body>
    <div class="container">
        @foreach (var item in Model)
        {
            <div class="item-container">
                <div class="img-container">
                    <img src="~/photos/@item.ImageUrl" />
                </div>
                <div class="body-container">
                    <div class="overlay">
                    </div>

                    <div class="event-info">
                        <p class="title">@item.Name</p>
                        <div class="separator"></div>
                        <p class="info">@item.ShortDescription</p>
                        <p class="price">@item.Price лв</p>

                        <div class="additional-info">
                            <p class="info"><i class="bi bi-geo-alt"></i>@item.Location.Name</p>
                            <p class="info"><i class="bi bi-stopwatch"></i>@item.Duration</p>

                            <p class="info descr">
                                @item.Description
                            </p>
                        </div>

                    </div>
                    <a class="action" asp-controller="EventReservations" asp-action="Create" asp-route-sportActivityId="@item.SportActivityId">Резервирай</a>
                </div>
            </div>
        }
       

   @*     <div class="item-container">
            <div class="img-container">
                <img src="~/photos/para1.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">С парапланер над Перник</p>
                    <div class="separator"></div>
                    <p class="info">около Вискяр планина</p>
                    <p class="price">85лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>около Вискяр планина, до с.Расник</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>10-30 мин</p>

                        <p class="info descr">
                            Тандемен полет с парапланер - Вискяр, Перник
                        </p>
                    </div>

                </div>
                <button class="action"><a asp-controller="EventReservations" asp-action="Create">Резервирай</a></button>
            </div>
        </div>

        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/snow5.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">С моторна шейна из Рила</p>
                    <div class="separator"></div>
                    <p class="info">близо до Рилските езера</p>
                    <p class="price">179лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>около Паничище, Рилски езера</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>1-3 часа</p>

                        <p class="info descr">
                            Стани част от потресаващата красота на Рила планина.
                        </p>
                    </div>

                </div>
                <button class="action"><a asp-controller="EventReservations" asp-action="Create" asp-area="">Резервирай</a></button>
            </div>
        </div>*@
@*
        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/skydive9.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">Скок над София</p>
                    <div class="separator"></div>
                    <p class="info">в близост до София</p>
                    <p class="price">390лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>в близост до София (Сапарева баня)</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>5-10 мин</p>

                        <p class="info descr">
                            Задължително приключение за всеки любител на адреналина!
                        </p>
                    </div>

                </div>
                <button class="action">Резервирай</button>
            </div>
        </div>

        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/bungee8.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">Скок от ЖП мост Буново</p>
                    <div class="separator"></div>
                    <p class="info">с. Буново</p>
                    <p class="price">60лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>с. Буново</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>8-10 мин</p>

                        <p class="info descr">
                            Избери да скочиш от рядко срещана и интересна локация.
                        </p>
                    </div>

                </div>
                <button class="action">Резервирай</button>
            </div>
        </div>

        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/balloon.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">Полет с балон над Белоградчик</p>
                    <div class="separator"></div>
                    <p class="info">в района на Белоградчик</p>
                    <p class="price">280лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>Белоградчишки скали</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>30-60 мин</p>

                        <p class="info descr">
                            Впусни се в едно от най-безопасните въздушни приключения – 
                            полет с топловъздушен балон над Белоградчик.
                        </p>
                    </div>

                </div>
                <button class="action">Резервирай</button>
            </div>
        </div>

        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/rafting3.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">Рафтинг по р.Струма + въжена градина</p>
                    <div class="separator"></div>
                    <p class="info">рафтинг център Симитли</p>
                    <p class="price">80лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>Кресненско дефиле</p>
                        <p class="info"><i class="bi bi-stopwatch"></i>около 2 часа</p>

                        <p class="info descr">
                            Наслади се на едно незабравимо, комбинирано, екстремно приключение,
                            включващо Рафтинг и въжена градина в Кресненското дефиле.
                        </p>
                    </div>

                </div>
                <button class="action">Резервирай</button>
            </div>
        </div>

        <div class="item-container">
            <div class="img-container">
                <img src="~/photos/rock.jfif" />
            </div>
            <div class="body-container">
                <div class="overlay">
                </div>

                <div class="event-info">
                    <p class="title">Виа ферата Мальовица</p>
                    <div class="separator"></div>
                    <p class="info">връх Куклата, Мальовица</p>
                    <p class="price">315лв</p>

                    <div class="additional-info">
                        <p class="info"><i class="bi bi-geo-alt"></i>връх Куклата, Мальовица</p>
                        <p class="info"><i class="bi bi-stopwatch"></i> 6 часа (катерене:2-3 часа) </p>

                        <p class="info descr">
                            За тези, които нямат опит в скалното катерене, но искат да усетят тръпката от алпинизма.
                        </p>
                    </div>

                </div>
                <button class="action">Резервирай</button>
            </div>
        </div>*@
    </div>
</body>

Adventum/Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Контакти";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adventum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/contacts.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Adventum.styles.css" asp-append-version="true" />
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
</head>
<body>
    <section class="contacts container-fluid bg-grey">
        <div class=content>
            <h1 class="heading">Контакти</h1>
            <p>
                Ще се радваме, ако имате някакви идеи или въпроси да се обърнете към нас.
                Отговаряме в рамките на 24ч.
            </p>
        </div>
        <div class="container">
            <div class="contact-info">
                <div class="box">
                    <div class="icon">
                        <i class="bi bi-geo-alt" aria-hidden="true"></i>
                    </div>
                    <div class="text">
                        <h3>Адрес</h3>
                        <p>
                            бул."3-ти март" №140, <br /> София, България
                        </p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon">
                        <i class="bi bi-telephone" aria-hidden="true"></i>
                    </div>
                    <div class="text">
                        <h3>Телефон</h3>
                        <p>
                            +359 123 123 123
                        </p>
                    </div>
                </div>
                <div class="box">
                    <div class="icon">
                        <i class="bi bi-envelope" aria-hidden="true"></i>
                    </div>
                    <div class="text">
                        <h3>Email</h3>
                        <p>
                            adventum@gmail.com
                        </p>
                    </div>
                </div>
            </div>
            <div class="contact-form">
                <form>
                    <h2>Изпрати съобщение</h2>
                    <div class="inputBox">
                        <input type="text" name="" required />
                        <span class="form-text">Имена</span>
                    </div>
                    <div class="inputBox">
                        <input type="text" name="" required />
                        <span class="form-text">Имейл</span>
                    </div>
                    <div class="inputBox">
                        <input type="text" name="" required />
                        <span class="form-text">Напишете Вашето съобщение...</span>
                    </div>
                    <div class="inputBox">
                        <input type="submit" name="" value="Send" />
                    </div>
                </form>
            </div>
        </div>
    </section>
    <div id="content-map">
        <div id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11736.868133612401!2d24.7459606!3d42.656756!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40a997279d5eee63%3A0x30c9e27df1c7136b!2z0J_RgNC-0YTQtdGB0LjQvtC90LDQu9C90LAg0LPQuNC80L3QsNC30LjRjyAi0JPQtdC9LiDQktC70LDQtNC40LzQuNGAINCX0LDQuNC80L7QsiI!5e0!3m2!1sbg!2sbg!4v1681736078677!5m2!1sbg!2sbg" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
    <section>
        <h2 class="titleFAQ">Често задавани въпроси</h2>
        <div class="faq">
            <div class="question" id="#q1">
                <button>
                    <h3>Какво е Adventum?</h3>
                    <ion-icon name="add-outline"></ion-icon>
                </button>
                <p>
                    <span>Adventum</span> е сайт за резервиране на екстремни събития, включващи различни екстремни спортове.
                </p>
            </div>
            <div class="question" id="#q2">
                <button>
                    <h3>Не съм навършил/а 18 години, мога ли да скоча с бънджи?</h3>
                    <ion-icon name="add-outline"></ion-icon>

                </button>

                <p>
                    Ако не си навършил/а 18 години все още, трябва да имаш позволението от родител/настойник,
                    както и да бъдеш придружен/а от него, независимо от спорта, който искаш да практикуваш.
                </p>
            </div>

            <div class="question" id="#q3">
                <button>
                    <h3>Има ли значение теглото?</h3>
                    <ion-icon name="add-outline"></ion-icon>
                </button>
                <p>Има значение. Минималните килограми са <span>40кг</span>, а ако клиентът тежи повече от <span>100кг</span> трябва да предупреди предварително екипа.</p>
            </div>

            <div class="question" id="#q4">
                <button>
                    <h3>Как да си запазя час/ден?</h3>
                    <ion-icon name="add-outline"></ion-icon>

                </button>
                <p>Резервация се прави от страницата за резервиране - бутон <span>РЕЗЕРВАЦИИ</span>. Избираш спорт, локация, удобен ден и ние ще се свържем с теб по имейл за допълнителна информация.</p>
            </div>

            <div class="question" id="#q5">
                <button>
                    <h3>Каква е валидността на ваучера?</h3>
                    <ion-icon name="add-outline"></ion-icon>

                </button>
                <p>Валидността на ваучера е <span>1 година</span> от деня на закупуването на ваучера.</p>
            </div>
        </div>

    </section>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script type="module" src="/js/contacts.js"></script>
</body>
</html>

Adventum/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Adventum";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Adventum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Adventum.styles.css" asp-append-version="true" />
</head>
<body>
    <section id="welcomeIMG">
        <img src="~/photos/homeGIF.gif" id="homeGIF" class="img-fluid" />
    </section>

    <div class="sports">

        <div class="item snow">
            @*<img class="imgSport" src="~/photos/snow.jfif"/>*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="SnowPage"><p class="sport-text">СКИ, СНОУБОРД, МОТОРНА ШЕЙНА</p></a>
            </div>
        </div>
        <div class="item ATV">
            @*<img class="imgSport"  src="~/photos/ATV.jfif" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="ATVpage"><p class="sport-text">ATV РАЗХОДКА</p></a>
            </div>
        </div>
        <div class=" item rafting">
            @*<img class="imgSport" src="~/photos/rafting.jpg" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="RaftingPage"><p class="sport-text">РАФТИНГ</p></a>
            </div>
        </div>
        <div class=" item rock">
            @*<img class="imgSport" src="~/photos/rock.jfif" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="ClimbPage"><p class="sport-text">СКАЛНО КАТЕРЕНЕ</p></a>
            </div>
        </div>
        <div class="item bungee">
            @*<img class="imgSport" src="~/photos/bungee.jfif" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="BungeePage"> <p class="sport-text">БЪНДЖИ СКОК</p></a>
            </div>
        </div>
        <div class="item balloon">
            @* <img class="imgSport" src="~/photos/balloon.jpg" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="BalloonPage"><p class="sport-text">ПОЛЕТ С/СКОК ОТ БАЛОН</p></a>
            </div>
        </div>
        <div class="item paragliding">
            @*<img class="imgSport" src="~/photos/paragliding.jpg" />*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="ParaPage"><p class="sport-text">ПОЛЕТ С ПАРАПЛАНЕР</p></a>
            </div>
        </div>
        <div class="item skydive">
            @*<img class="imgSport" src="~/photos/skydiving.jfif"/>*@
            <div class="overlay">
                <a asp-area="" asp-controller="Sports" asp-action="SkydivePage"><p class="sport-text">СКОК ОТ САМОЛЕТ</p></a>
            </div>
        </div>
    </div>
</body>
</html>